name: gitleaks

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: security-gitleaks-config
      run: |
        git clone https://github.com/alangonzalez/gitleaks-global-config && cp gitleaks-global-config/security/* . 
    - run: |
        ls -ltr * && pip3 install toml && python3 gitleaks_config_generator.py && ls -ltr * && head -50 global_config.toml
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: global_config.toml
