name: gitleaks

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: security-gitleaks-config
      run: |
        git clone https://github.com/alangonzalez/gitleaks-global-config
    - run: |
        ls -ltr *
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master
      with:
        config-path: gitleaks-global-config/security/gitleaks.global.toml
