on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        generateSarif: 1
      continue-on-error: true
 # https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
 # Optional.
    - name: "Upload artifact"
      uses: actions/upload-artifact@v2
      with:
          name: SARIF file
          path: semgrep.sarif
          retention-days: 30
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: semgrep.sarif
