on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        generateSarif: 1
    - name: JSON Report
      run: |
        find . -name '*.json' -print
#    - name: SARIF Report
#      run: |
#        find . -name '*.sarif' -exec cat {} \;
