on:
  pull_request: {}
  push:
    branches:
    - main
    - master
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        generateSarif: 1
    - name: GetChangedFiles
      run: |
        find . -name '*.sarif' -print
    - name: Commit back SARIF (if it was missing)
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "build(semgrep): Commit the newly-generated SARIF file"
