name: SpectralSecrets

on:
  pull_request: {}
  push:
    branches:
    - main
    - master
  workflow_dispatch:

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
  
jobs:
  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl -L "https://get.spectralops.io/latest/x/sh?dsn=$SPECTRAL_DSN" | sh
      - name: Scan
        run: $HOME/.spectral/spectral scan --ok
